# Generated by Django 4.2 on 2026-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythix_libraryapp', '0005_book_book_type_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
