# Generated by Django 4.2 on 2026-03-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythix_libraryapp', '0006_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Residential_Address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
    ]
