# Generated by Django 4.2 on 2026-03-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ythix_libraryapp', '0007_profile_residential_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ythix_libraryapp.publisher'),
        ),
    ]
